### PR TITLE
Merge in the SSH Cloud feature

### PR DESCRIPTION
**Pull request by deserted-operative**
This pull request marks the end of the Milestone 2 development of SSH Cloud.

It includes the addition of functionality for:
- the MySQL database server, run in its own container by the `docker-compose` file.
- the SSH Cloud server that accepts requests from client applications, and responds accordingly.
- unit testing the SSH Cloud features as outlined in the Documentation as of Milestone 2.

### CODE REVIEW

**Comment by deserted-operative** [comment]
Closing this pull request to re-open, as it appears that the updated SSH CI Workflow hasn't been picked up in this pull request.

**Comment by deserted-operative** [comment]
Again closing this pull request to re-open, so that the check for this pull request pulls the updated yml action file.

**Comment by deserted-operative** [comment]
Again closing this pull request to re-open, so that the check for this pull request pulls the updated yml action file.

**Comment by deserted-operative** [comment]
Again closing this pull request to re-open, so that the check for this pull request pulls the updated yml action file.

**Comment by deserted-operative** [comment]
Again closing this pull request to re-open, so that the check for this pull request pulls the updated yml action file.

**Comment by deserted-operative** [comment]
Again closing this pull request to re-open, so that the check for this pull request pulls the updated yml action file.

**Comment by deserted-operative** [comment]
Hey everyone!

I just wanted to apologise for the _excessive_ number of closes and re-opens on this pull request; I struggled with debugging the CI workflow...

If you could all have a review of the code, I'd be super grateful, so we can get this merged into `main` ASAP.

---

@G-Henderson @parlatellioglu @Hasan24642

**Comment by G-Henderson** [comment]
Damn! Nice work @Harvlovescactus!! Looks good to me.

**Review by G-Henderson — APPROVED** [review]

**Comment by Hasan24642** [comment]
Great work!

**Pull request merged**
